/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as colorBoxSol from "./ColorBox.sol";
export type { colorBoxSol };
import type * as test from "./test";
export type { test };
