/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ColorBox__factory } from "./ColorBox__factory";
export { ColorBox4__factory } from "./ColorBox4__factory";
