/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20Token } from "./MockERC20Token";
export type { MockV3Aggregator } from "./MockV3Aggregator";
